# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: lixin521
    ports:
      - 27018:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: lixin521
      ME_CONFIG_MONGODB_URL: mongodb://root:lixin521@mongo:27017/
  nestjs_app:
    build: .
    restart: always
    ports:
      - 3000:3001
    depends_on:
      - mongo
